name: dawri_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.0.0
  intl: ^0.20.2 
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  flutter_rating_bar: ^4.0.1
  group_button: ^5.3.4
  flutter_spinbox: ^0.13.1
  rflutter_alert:
  firebase_messaging: ^15.2.4
  shared_preferences: ^2.5.2
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.6
  sign_in_with_apple: ^7.0.1
  timeline_tile: ^2.0.0
  font_awesome_flutter: ^10.8.0
  flutter_local_notifications: ^19.1.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0  

flutter:
  uses-material-design: true

  assets:
    - images/feedback.png
    - images/notif.png
    - images/booking.png
    - images/welcome.png
    - images/sp.png
    - images/restaurant.png
    - images/Cafes.png
    - images/Banks.png
    - images/Events.png
    - images/HealthCare.png
    - images/google.jpg
    - images/apple.jpg
    - images/Q.png